title: Georges CPAP
lang: en
description: This fully printable device with no moving parts is able to provide a continuous positive pressure to a patient's airways while letting them breathe freely.

remote_theme: rundocs/jekyll-rtd-theme

edit: true

copyright:
  revision: true

addons:
  - github
  - plugins
  - analytics

addons_branch: true

# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions